# Generated by Django 5.0.6 on 2025-01-29 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0003_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=2500)),
                ('book_name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('pages', models.IntegerField()),
                ('trending', models.BooleanField(default=False)),
                ('editor_choice', models.BooleanField(default=False)),
                ('popular_classic', models.BooleanField(default=False)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_books', to='books.genre')),
            ],
        ),
    ]
